### ISSUE TITLE
No sounds

### ISSUE THREAD

**Issue by RaibowFairy** [mangband/mangband#1155]
Ingame sounds don't work.

**Comment by grking** [comment]
I think this is fixed in the repackaged client download

**Comment by RaibowFairy** [comment]
still no sound, 1.1.4

**Comment by evileye-uk** [comment]
Windows? vi mangclient.ini
Change the line that says Sound=0 to Sound=1 and see if they still don't work.

**Comment by evileye-uk** [comment]
Sound worked in the 1.1.4 download on Windows 10 when settings were changed as above.

**Comment by grking** [comment]
Download the 1.1.4 client again (it's been re-packaged), the filename should end with "v1.1.4-2.exe".

Then to go the Options menu and check the "Sound" box.
